django_mpct_proj/django_mpct_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mpct/', include('mpct_app.urls')), # www.domain.com/mpct/...(app urls)
    path('',RedirectView.as_view(url='mpct/')), # delete or set up bebore deploy
]

django_mpct_proj/mpct_app/urls.py
from django.urls import path 
from . import views 

app_name = 'mpct_app'

urlpatterns = [
    path('', views.home_view, name='home_view'),
    
    path('material_list', views.MaterialListView.as_view(), name='material_list_view'),
    path('material_detail_func/<int:pk>', views.material_detail_view, name='material_detail_func'),

    path('certificate_list', views.CertificateListView.as_view(), name='certificate_list_view'),
    path('certificate_detail/<str:pk>', views.certificate_detail_view, name='certificate_detail_view'),

    path('register_material', views.register_material, name='register_material'),
    path('material_type_create', views.MaterialTypeCreateView.as_view(), name='material_type_create_view'),
    path('specification_create', views.SpecificationCreateView.as_view(), name='specification_create_view'),

    path('check_certificate/<str:grade>/<int:pk>', views.check_certificate_view, name='check_certificate'),
    path('search_heat_number', views.search_heat_number, name='search_heat_number'),
]



"""
urlpatterns = [
    path('material/', material_view, name='material_view'),
    path('ajax/load-materials/', load_materials, name='ajax_load_materials'),
]
"""

django_mpct_proj/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if title %} {{title}} {% else %} MPCT {% endif %}</title>
    <link href="{% static 'CSS/bootstrap_min.css' %}" rel="stylesheet">
    <link href="{% static 'CSS/custom.css' %}" rel="stylesheet">
{% comment %} {% static "bootstrap_min.css" %} {% endcomment %}
</head>
<body class="container bg-dark border-bottom border-body" data-bs-theme="dark">
    <header>
        <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'mpct_app:home_view' %}">MPCT</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'mpct_app:material_list_view' %}">Materials</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'mpct_app:certificate_list_view' %}">Certificates</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  MI
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'mpct_app:register_material' %}">Register a new material and its requirements</a></li>
                  <li><a class="dropdown-item" href="{% url 'mpct_app:material_type_create_view' %}">Register a new material type</a></li>
                  <li><a class="dropdown-item" href="{% url 'mpct_app:specification_create_view' %}">Register a new Specification</a></li>
                  <!--
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                  -->
                </ul>
              </li>

            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search heat humber</button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    
      <section>
        <!-- Content -->
        <div class="container">
            {% block content %}{% endblock %}

            <footer>
              <p> 
                <a href="https://chevron.sharepoint.com/:u:/r/sites/RE/SitePages/Mechanical-Integrity.aspx?csf=1&web=1&e=CVSzD1">Mechanical Integrity Team</a>
              </p>
              <p>
                <a href="mailto:micon@tengizchevroil.com">@micon</a>
              </p>
            </footer>
        </div>

      </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>